### PR TITLE
WIP: Allow sf players to pickup items summoned by other in-range sf players

### PR DESCRIPTION
**Pull request by fuzzlecutter**
Looking for feedback on this approach to enable self-found (non-solo) players to utilize magician's summoned items. Haven't tested this yet.

### CODE REVIEW

**Comment by SecretsOTheP** [comment]
Liking the approach. I'll send friends of PQ after it.

**Comment by cord-b** [comment]
Might be a super edge case, but you could get around the level limit by leapfrogging to lower and lower level toons: 60 drops for a 40. 40 re-drops for a 30. 30 re-drops for 20, and so on. May need to set dropper level based on the spell level instead of the toon.

**Comment by SecretsOTheP** [comment]
Could just limit this to 'those summoned item spells will affect the target if grouped and self found'

**Comment by fuzzlecutter** [comment]
> > Could just limit this to 'those summoned item spells will affect the target if grouped and self found'
> 
> I assumed (perhaps incorrectly) that changing a spell's target from self-only to other would involve a spells_en.txt change. If that's not correct, where are spells target type defined?

I see that in the client's spdat.eff that modulation rod's targettype is self, while the `spells_en` and `spells_new` tables on the server have targettype other for modulation rod. I suppose that the server's definitions override the client's spdat.eff.

I'll make another pr to update the spell tables so that all summon spells will have a targettype like mod rod currently does.

**Comment by fuzzlecutter** [comment]
https://github.com/SecretsOTheP/EQMacEmu/pull/147 makes additional summon item spells similar to mod rod, which is already castable on others.

**Comment by fuzzlecutter** [comment]
Closing this in favor of #147

**Pull request closed without merging**
